name: Build Teleport Connect for Windows
on: 
  push:
    branches:
      - tcsc/gha-arm-builds
jobs:
  build:
    name: Build ARM32 devices
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Check GLIBC version
        uses: docker://arm32v8/centos:7
        with: 
          entrypoint: ldd
          args:  --version

